# Base eslint config on prettier rules.
extends:
  - plugin:prettier/recommended
plugins:
  - import
parserOptions:
  # We use ecma version 13, which supports private class fields.
  ecmaVersion: 13
env:
  node: true
  mocha: true
  # Including browser will allow use of environment-provided global variables such as 'window'
  # which is not otherwise defined.
  browser: true
rules:
  no-console: 0
  # Sometimes I like a single 'return' statement in a full bloc, e.g. see the
  # tests, so relax the requirement to have single return statements
  arrow-body-style: 0
  import/no-extraneous-dependencies:
    [error, { devDependencies: ["**/*.specs.js","webpack.config.js"] }]
  no-process-exit: 0
  no-param-reassign:
    [
      "error",
      {
        "props": true,
        # $scope appears in angular sample app
        "ignorePropertyModificationsFor": ["$scope"],
      },
    ]
